export const environment = {
  production: true,
  loginURL:"https://innova.cochabamba.bo/api/auth/login",
  historialBoletasURL:"https://camposdeportivos.cochabamba.bo/api/get-list-boleta",
  detalleBoletaURL: "https://camposdeportivos.cochabamba.bo/api/boleta/get-detalle-boleta",
  listaSubalcaldias: "https://camposdeportivos.cochabamba.bo/api/oficinas",
  listadoCamposDeportivos: "https://camposdeportivos.cochabamba.bo/api/campodeportivo/",
  detalleCampoDeportivo: "https://camposdeportivos.cochabamba.bo/api/campodeportivo/id/",
  listaDeHoras: "https://camposdeportivos.cochabamba.bo/api/campodeportivo/ocupados",
  verifReserva: "https://camposdeportivos.cochabamba.bo/api/reservacampodep/verification",
  saveReserva: "https://camposdeportivos.cochabamba.bo/api/reservacampodep",
  getCI: "https://innova.cochabamba.bo/api/usuario/",
  generarBoleta: "https://camposdeportivos.cochabamba.bo/api/reservacampodep/generar-boleta",
  listaDeTodosLosCamposDeportivos: "https://camposdeportivos.cochabamba.bo/api/campodeportivo",
  catastroURL: "http://192.168.105.219:6080/arcgis/services/",
  consulta_infracciones: "https://busquedasgamc.cochabamba.bo/web/index.php?r=services/get-infringement",
  patente: "https://www.cochabamba.bo/api/municipio/sitiosjson",
  // citizenRegistration: "https://innova.cochabamba.bo/api/v1/citizen-registration",
  generarPagoQR: "https://multiserv.cochabamba.bo/api/v1/pay/qr/generated",
  anularPagoQR: "https://multiserv.cochabamba.bo/api/v1/pay/qr/update/status",
  apiTramites: "https://innova.cochabamba.bo/",
  apiCorrespFile: "https://repositoriogamc.cochabamba.bo/api/v1/repository/upload-file",
  apiNewCorresp: "https://innova.cochabamba.bo/api/v1/correspondencia/create",
  apiSendCorresp: "https://multiserv.cochabamba.bo/api/v1/atlas/enviar-correspondencia",
  apiSeguCorresp: "https://multiserv.cochabamba.bo/api/v1/atlas/seguimiento-tramite",
  uploadAvatar: "https://repositoriogamc.cochabamba.bo/api/v1/repository/upload-avatar",
  registroUsuario: "https://multiserv.cochabamba.bo/api/v1/registro-ciudadano",
  apiQuestions: "https://centralllamadas.cochabamba.bo/obtain_questions"
};
